import { chromium } from './node_modules/playwright-core/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
const browser = await chromium.connectOverCDP('http://127.0.0.1:9223');
const page = browser.contexts()[0].pages().find(p => p.url().includes('5173'));
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
const session = await page.context().newCDPSession(page);
await session.send('Network.enable');
await session.send('Network.setCacheDisabled', { cacheDisabled: true });
await page.reload();
await page.waitForFunction(() => document.querySelector('canvas')?.dataset.artwork === 'ready', { timeout: 60000 });
await page.getByRole('button', { name: 'Export 10s clip' }).waitFor();
await page.screenshot({ path: 'C:/Users/Lenovo/build-sprint-app/tmp/royal-portrait/passport-painted.png' });
console.log(JSON.stringify({ artwork: await page.locator('canvas').getAttribute('data-artwork'), exportEnabled: await page.getByRole('button', { name: 'Export 10s clip' }).isEnabled(), errors }));
await session.send('Network.setCacheDisabled', { cacheDisabled: false });
await page.bringToFront();
await browser.close();
if (errors.length) process.exitCode = 1;
