import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { readFile } from 'node:fs/promises';
const portfolioCode = await readFile(new URL('../src/portfolio.js', import.meta.url), 'utf8');
const portfolioUrl = 'data:text/javascript;base64,' + Buffer.from(portfolioCode).toString('base64');
const editionCode = (await readFile(new URL('../src/edition.mjs', import.meta.url), 'utf8')).replace('./portfolio.js', portfolioUrl);
const { bindEdition, currentEdition, loadingMarkup, rowsMarkup } = await import('data:text/javascript;base64,' + Buffer.from(editionCode).toString('base64'));
const root = () => new JSDOM('<main><p id="edition-date"></p><p id="edition-note"></p><div id="positions"></div></main>', { url: 'http://localhost' });
const markup = new JSDOM(rowsMarkup(currentEdition)).window.document;
assert.equal(markup.querySelectorAll('article').length, 11);
assert.deepEqual([...markup.querySelectorAll('h3')].map(node => node.textContent), ['CEG', 'GRID', 'ICLN', 'FLKR', 'SMH', 'AMZN', 'GOOG', 'MSFT', 'QQQ', 'AAPL', 'TSLA']);
assert.equal(markup.querySelectorAll('.status').length, 11);
assert.equal(markup.querySelectorAll('a[target="_blank"]').length, 11);
console.log('PASS: 11 positions, stage order, alphabetical tickers, statuses and source links.');
const first = root();
await bindEdition(first.window.document, async () => null, first.window.localStorage);
assert.equal(first.window.document.querySelectorAll('article').length, 11);
assert.equal(first.window.document.querySelectorAll('.status').length, 0);
assert.equal(first.window.document.querySelector('#edition-date').hidden, true);
console.log('PASS: first visit without an edition shows positions and inclusion reasons without statuses.');
const returning = root();
await bindEdition(returning.window.document, async () => currentEdition, returning.window.localStorage);
await bindEdition(returning.window.document, async () => null, returning.window.localStorage);
assert.equal(returning.window.document.querySelectorAll('.status').length, 11);
assert.equal(returning.window.document.querySelector('#edition-note').textContent, 'The next edition lands Saturday 10 AM IST.');
console.log('PASS: returning visit without a new edition shows the saved latest edition and Saturday timing.');
assert.equal(new JSDOM(loadingMarkup()).window.document.querySelectorAll('.skeleton-row').length, 11);
const failed = root();
let calls = 0;
await bindEdition(failed.window.document, async () => { if (!calls++) throw new Error('Failed'); return currentEdition; });
assert.equal(failed.window.document.querySelector('[role="alert"]').textContent, 'Rows failed to load.Refresh');
failed.window.document.querySelector('button').click();
await new Promise(resolve => setImmediate(resolve));
assert.equal(failed.window.document.querySelectorAll('article').length, 11);
console.log('PASS: loading has 11 row shimmers; failed loading displays Refresh, which successfully reloads the edition.');

