import {ConvexHttpClient} from 'convex/browser';
import {api} from '../convex/_generated/api.js';
import {stockTakeaway,restricted} from '../shared/holdings.mjs';
import {emailMarkup,bindEmail} from './standing.mjs';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function bindHoldings(app){
 document.body.classList.add('holdings-body');
 const client=new ConvexHttpClient(import.meta.env.VITE_CONVEX_URL);
 let token=new URLSearchParams(location.search).get('session'),view,items=[],running=-1;
 const frame=html=>{app.innerHTML=`<div class="holdings-page"><header><a href="/">Lookout</a><a href="/">Back to home</a></header><main><h1>My holdings</h1>${html}</main></div>`;};
 const read=async()=>{view=await client.query(api.holdings.read,{token});if(!view)throw Error('This draft could not be found.');};
 function entry(){frame(`<p class="holdings-lead">Your stocks. Your reasons. A check against the last 30 days.</p><form id="holdings-entry" class="holdings-card"><label for="holdings-text">Your stocks and reasons</label><textarea id="holdings-text" required maxlength="6000" rows="7" placeholder="Stock name, followed by the reasons behind it."></textarea><button class="holdings-primary">Review my reasons</button><p role="status" id="holdings-note"></p></form>`);app.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button'),note=app.querySelector('#holdings-note');button.disabled=true;note.textContent='Reading your reasons…';try{const result=await client.action(api.holdingsActions.interpret,{text:app.querySelector('textarea').value});token=result.token;history.replaceState(null,'',`?create=holdings&session=${token}`);await read();items=view.lines.map(({stock,reasons})=>({stock,reasons}));review();}catch(error){note.textContent=/daily spending|thinking limit/.test(String(error))?'Check stopped: daily spending limit reached. Try again tomorrow.':'Could not read your reasons. Please try again.';button.disabled=false;}};}
 function review(){frame(`<p class="holdings-lead">Check what we understood. Edit any name or reason before continuing.</p><form id="holdings-review">${items.map((item,i)=>`<section class="holdings-card"><label for="stock-${i}">Stock</label><input id="stock-${i}" data-stock="${i}" value="${esc(item.stock)}" maxlength="150" required><p class="holdings-match" id="match-${i}"></p><label for="reasons-${i}">Your reasons · one per line</label><textarea id="reasons-${i}" data-reasons="${i}" rows="3">${esc(item.reasons.join('\n'))}</textarea><button type="button" class="holdings-remove" data-remove="${i}">Remove entry</button></section>`).join('')}<button class="holdings-primary" ${items.length?'':'disabled'}>Confirm and check last 30 days</button><p id="holdings-note" role="status"></p></form>`);
 app.querySelectorAll('[data-stock]').forEach(input=>{const update=async()=>{items[+input.dataset.stock].stock=input.value;const match=await client.query(api.holdings.match,{name:input.value});const label=app.querySelector(`#match-${input.dataset.stock}`);if(label)label.textContent=match?`${match.name} · ${match.ticker} · ${match.market}`:'Not supported yet';};input.oninput=()=>items[+input.dataset.stock].stock=input.value;input.onblur=update;void update();});
 app.querySelectorAll('[data-reasons]').forEach(input=>input.oninput=()=>items[+input.dataset.reasons].reasons=input.value.split('\n').filter(x=>x.trim()));
 app.querySelectorAll('[data-remove]').forEach(button=>button.onclick=()=>{items.splice(+button.dataset.remove,1);review();});
 app.querySelector('form').onsubmit=async e=>{e.preventDefault();const note=app.querySelector('#holdings-note');if(items.some(x=>restricted(x.stock+' '+x.reasons.join(' ')))){note.textContent='Please rephrase your entry using the business reasons you want checked.';return;}e.target.querySelector('button.holdings-primary').disabled=true;note.textContent='Starting the evidence checks…';try{await client.mutation(api.holdings.confirm,{token,items});await read();await checkAll();}catch(error){running=-1;await read();results();app.querySelector('#holdings-progress').textContent='Check stopped. Refresh to see completed results.';}};
 }
 async function checkAll(){running=view.lines.findIndex(line=>line.match&&!line.result);results();try{await client.action(api.holdingsActions.checkAll,{token});}finally{running=-1;await read();results();}}
 function results(){frame(`<p class="holdings-lead">Your reasons, checked against recent evidence.</p><p id="holdings-progress" role="status">${running>=0?'Checking '+esc(view.lines[running].stock)+'…':''}</p>${view.lines.map((line,i)=>`<article class="holdings-card"><h2>${esc(line.match?.name||line.stock)}</h2>${line.match?`<p class="holdings-match">${esc(line.match.ticker)} · ${esc(line.match.market)}</p>`:''}<p class="holdings-takeaway">${esc(line.error|| (line.result?stockTakeaway(line.result.assumptions):running===i?'Checking the last 30 days…':'Evidence check not completed.'))}</p>${line.result?`<p class="holdings-window">${esc(line.result.windowStart)} to ${esc(line.result.windowEnd)}</p>${line.result.assumptions.map(row=>`<section class="holdings-reason"><h3>${esc(row.assumption)}</h3><p class="holdings-labels"><strong>${esc(row.status)}</strong><span>Signal strength: ${esc(row.signalStrength)}</span></p><p>${esc(row.reason)}</p>${row.sources.map(s=>`<p class="holdings-source"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(restricted(s.title)?'Read source':s.title)}</a><br>${esc(s.publisher)} · ${esc(s.date)} · Date verified on publisher page</p>`).join('')}</section>`).join('')}`:line.reasons.map(reason=>`<p>${esc(reason)}</p>`).join('')}</article>`).join('')}${running<0&&view.lines.some(line=>line.match&&!line.result)?'<button id="holdings-retry" class="holdings-primary">Continue evidence checks</button>':''}<section class="holdings-card holdings-signup"><h2>Keep checking your reasons</h2><p>Save these stocks and reasons for your weekly check.</p>${emailMarkup()}</section>`);const retry=app.querySelector('#holdings-retry');if(retry)retry.onclick=()=>void checkAll();bindEmail(app.querySelector('.holdings-signup'),email=>client.action(api.holdingsActions.subscribe,{token,email}));}
 try{if(token){await read();if(view.confirmed)results();else{items=view.lines.map(({stock,reasons})=>({stock,reasons}));review();}}else entry();}catch{entry();app.querySelector('#holdings-note').textContent='This draft could not be opened. Start a new one.';}
}
